### ISSUE TITLE
When saving and loading a single preset, semitone is off-by-one

### ISSUE THREAD

**Issue by basdp** [dsp56300/gearmulator#75] opened 2022-03-13 10:23 UTC
When saving a patch with the save button on top, and then loading the patch, the semitone of -1 for some of the osc (might be all). I suspect there might be more off-by-one issues with saving/loading patches.

I think it is in the saving stage, not loading.

Version: v1.2.10
Platform: MacOS and Windows (Linux not tested)
DAW: Bitwig
ROM: Virus C 6v6

**Comment by dsp56300** [comment] 2022-04-07 19:14
dupe of #83

**Closed by dsp56300** 2022-04-07 19:14 UTC

**Comment by basdp** [comment] 2022-04-07 20:21
I'm note sure if this is a dupe per se, as I have this on OSC 1. Just for completeness :-)
